CLIENTE = """
SELECT CLI_EMPRESA, CLI_CODIGO, CLI_NOMBRE, CLI_VENDEDOR, EXT_NOMBREFAC, EXT_MONEDA, EXT_NIVPRECIO, EXT_EXTRA6, CLA_DESCRIPCION AS TIENDA, EXT_EXTRA7, CLC_DESCRIPCION AS CADENA FROM MASTCLI
JOIN CLIENTES_EXTRA 
ON CLI_CODIGO = EXT_CLIENTE 
JOIN CLASIFICA_CLIENTES CLAS 
ON CLA_CODIGO = EXT_EXTRA6
JOIN CLASI_CUENTAS_CLI
ON CLC_CODIGO = EXT_EXTRA7 
  AND CLC_EMPRESA =CLI_EMPRESA 
  AND CLA_EMPRESA = EXT_EMPRESA 
  AND CLI_EMPRESA = EXT_EMPRESA
WHERE CLI_CODIGO LIKE %s AND CLI_EMPRESA = %s
ORDER BY CLI_CODIGO """