#
#   query de clientes, productos, devoluciones
#   usados en el menu de operaciones clientes y rutas
#
GET_CORR_NUMERO="""
DECLARE @DEVNUMERO INT 
set @DEVNUMERO = (
    SELECT CORR_NUMERO 
    FROM CORRELATIVO 
    WHERE CORR_TIPO = 'DCD' AND CORR_EMPRESA = 'PAN')
"""
UPDATE_CORR_NUMERO ="""
UPDATE CORRELATIVO SET CORR_NUMERO = ? 
WHERE CORR_TIPO = 'DCD' 
  AND CORR_EMPRESA = 'PAN'
"""

REF="""
SELECT
RTRIM(DINDCH_EMPRESA) AS DINDCH_EMPRESA, 	--00  COD EMPRESA 
RTRIM(DINDCH_DEVNUMERO) AS DINDCH_DEVNUMERO, 	--01  CORRELATIVO
RTRIM(DINDCH_VENDEDOR) AS DINDCH_VENDEDOR,	--02  RUTA|COD VENDEDOR
RTRIM(DINDCH_CLICODIGO) AS DINDCH_CLICODIGO,	--03  CODIGO CLIENTE
RTRIM(DINDCH_FECHA) AS DINDCH_FECHA,		--04  FECHA TIPO ORDINAL  = 4589
RTRIM(DINDCH_TIPDEV) AS DINDCH_TIPDEV,		--05  (WALMART : "R", UNISUPER: "V" , OTROS: "C")
RTRIM(DINDCH_NUMRECL) AS DINDCH_NUMRECL,		--06  NUMERO DOC. WALMAR, UNISUPER, 
RTRIM(DINDCH_LOTERECL) AS DINDCH_LOTERECL,   --07
RTRIM(DINDCH_FECHARECLA) AS DINDCH_FECHARECLA,	--08  FECHA DOC RECLAMO ORDINAL = 4589
DINDCH_STATUS,		--09  DEFAULT: V  (USO DE QSYSTEM)
DINDCH_NUMINVEN,	--10 DEFAULT 0 (USO DE QSYSTEM)
DINDCH_TIPINGRESO,	--11 DEFAULT "O"
DINDCH_HORA,		--12 HORA FORMATO ORDINAL 4695
CONVERT(FLOAT,DINDCH_TOTAL) AS DINDCH_TOTAL		--13 GRAN TOTAL SUMA DE LINEAS PRODUCTO
FROM DIST_INVDEVOLCLIH
WHERE DINDCH_NUMRECL = ? and DINDCH_NUMRECL != ''
"""


GLN_WALMART = """SELECT TOP 1 
CGPS_EMPRESA,
RTRIM(CGPS_CLIENTE) AS CGPS_CLIENTE,
RTRIM(CGPS_COD) AS CGPS_COD,
RTRIM(CGPS_GLN) AS CGPS_GLN
FROM CLIENTES_GPS
WHERE CGPS_COD =  '{0}' """

CLIENTE_NOMBRE = """ 
SELECT TOP 50
CLI_EMPRESA,
CLI_CODIGO,
RTRIM(CLI_NOMBRE) AS CLI_NOMBRE,
EXT_EXTRA6,
EXT_EXTRA7
FROM MASTCLI
JOIN CLIENTES_EXTRA
ON CLI_CODIGO = EXT_CLIENTE AND CLI_EMPRESA = EXT_EMPRESA
WHERE CLI_NOMBRE LIKE '%{0}%' AND (CLI_EMPRESA != 'PH1')
ORDER BY CLI_NOMBRE 
"""
CLIENTE = """
SELECT
    RTRIM(CLI_EMPRESA) as CLI_EMPRESA, 
    RTRIM(CLI_CODIGO) AS CLI_CODIGO, 
    RTRIM(CLI_NOMBRE) AS CLI_NOMBRE,
    CLI_VENDEDOR,
    RTRIM(CGPS_COD) AS CGPS_COD,
    RTRIM(VEN_NOMBRE) AS VEN_NOMBRE,
    RTRIM(EXT_NOMBREFAC) AS EXT_NOMBREFAC,
    EXT_MONEDA,
    EXT_NIVPRECIO,
    EXT_EXTRA6, 
    RTRIM(CLA_DESCRIPCION collate SQL_Latin1_General_CP1_CI_AS) AS TIENDA, 
    EXT_EXTRA7,
    RTRIM(CLC_DESCRIPCION) AS CADENA
FROM MASTCLI
LEFT JOIN CLIENTES_EXTRA 
ON CLI_CODIGO = EXT_CLIENTE AND  CLI_EMPRESA = EXT_EMPRESA
LEFT JOIN CLASIFICA_CLIENTES CLAS 
ON CLA_CODIGO = EXT_EXTRA6 AND CLI_EMPRESA = CLA_EMPRESA
LEFT JOIN VENDEDOR
ON VEN_CODIGO = CLI_VENDEDOR   AND CLI_EMPRESA = VEN_EMPRESA
LEFT JOIN CLIENTES_GPS
ON CLI_CODIGO = CGPS_CLIENTE  --collate latin1_general_ci_as
LEFT JOIN CLASI_CUENTAS_CLI
ON CLC_CODIGO = EXT_EXTRA7 AND CLI_EMPRESA = CLC_EMPRESA 
WHERE CLI_CODIGO LIKE %s AND CLI_EMPRESA = %s
ORDER BY CLI_CODIGO"""

CLIENTE_EXTERNO="""
SELECT
    RTRIM(CLI_EMPRESA) as CLI_EMPRESA, 
    RTRIM(CLI_CODIGO) AS CLI_CODIGO, 
    RTRIM(CLI_NOMBRE) AS CLI_NOMBRE,
    CLI_VENDEDOR,
    RTRIM(CGPS_COD) AS CGPS_COD,
    RTRIM(VEN_NOMBRE) AS VEN_NOMBRE,
    RTRIM(EXT_NOMBREFAC) AS EXT_NOMBREFAC,
    EXT_MONEDA,
    EXT_NIVPRECIO,
    EXT_EXTRA6, 
    EXT_EXTRA7
FROM MASTCLI
LEFT JOIN CLIENTES_EXTRA 
ON CLI_CODIGO = EXT_CLIENTE AND  CLI_EMPRESA = EXT_EMPRESA
LEFT JOIN VENDEDOR
ON VEN_CODIGO = CLI_VENDEDOR   AND CLI_EMPRESA = VEN_EMPRESA
LEFT JOIN CLIENTES_GPS
ON CLI_CODIGO = CGPS_CLIENTE  --collate latin1_general_ci_as
LEFT JOIN CLASI_CUENTAS_CLI
ON CLC_CODIGO = EXT_EXTRA7 AND CLI_EMPRESA = CLC_EMPRESA 
WHERE CLI_CODIGO = ? AND CLI_EMPRESA = ?
ORDER BY CLI_CODIGO
"""



RUTA ="""
SELECT 
VEN_CODIGO,
VEN_COMISION,
RTRIM(VEN_NOMBRE) as VEN_NOMBRE,
VXT_BODEGA,
VXT_BONIFICACION,
VXT_EMPRESA,
VXT_MIN_MULTA,
VXT_MONEDA,
VXT_NIVPRECIO,
RTRIM(VXT_MONEDADEF) AS VXT_MONEDADEF,
VXT_NIVPRECDEF,
VXT_MULTFINAN,
VXT_PORCMULTA,
VXT_PORCMULTA,
RTRIM(VXT_SISTEMA) AS VXT_SISTEMA,
VXT_TIPOLIQUIDAC,
VXT_UNIDCAMBIO
FROM VENDEDOR 
LEFT JOIN VENDEDOR_EXTRA 
ON VXT_VENDEDOR = VEN_CODIGO AND VEN_EMPRESA = VXT_EMPRESA
WHERE VEN_CODIGO = ? AND VEN_EMPRESA = ?
ORDER BY VEN_CODIGO
"""




PRODUCTO = """
SELECT
  RTRIM(INV_EMPRESA) AS INV_EMPRESA,
  RTRIM(INV_NOMBRE)  AS INV_NOMBRE,
  RTRIM(INV_UNIDAD)  AS INV_UNIDAD,
  RTRIM(OTR_INVENTARIO) AS OTR_INVENTARIO,
  RTRIM(OTR_MONEDA) AS OTR_MONEDA,
  INV_COSPROM,
  INV_ULTCOSTO,
  OTR_PRECIO1,
  OTR_PRECIO2,
  OTR_PRECIO3,
  OTR_PRECIO4,
  OTR_PRECIO5,
  OTR_PRECIO6,
  INV_COSPROM,
  INV_ULTCOSTO,
  INV_COSTO_REF
FROM OTROS_PRECIOS
JOIN MASTINVPOS
ON OTR_INVENTARIO = INV_INVENTARIO AND OTR_EMPRESA = INV_EMPRESA
WHERE OTR_INVENTARIO = '{0}'
AND  OTR_MONEDA = (SELECT EXT_MONEDA FROM CLIENTES_EXTRA 
	WHERE EXT_CLIENTE = '{1}' AND EXT_EMPRESA = '{2}')
AND OTR_EMPRESA = '{2}' 
"""

PRODUCTO_RUTA="""
SELECT
  RTRIM(INV_EMPRESA) AS INV_EMPRESA,
  RTRIM(INV_NOMBRE)  AS INV_NOMBRE,
  RTRIM(INV_UNIDAD)  AS INV_UNIDAD,
  RTRIM(OTR_INVENTARIO) AS OTR_INVENTARIO,
  RTRIM(OTR_MONEDA) AS OTR_MONEDA,
  INV_COSPROM,
  INV_ULTCOSTO,
  OTR_PRECIO1,
  OTR_PRECIO2,
  OTR_PRECIO3,
  OTR_PRECIO4,
  OTR_PRECIO5,
  OTR_PRECIO6,
  INV_COSPROM,
  INV_ULTCOSTO,
  INV_COSTO_REF
FROM OTROS_PRECIOS
JOIN MASTINVPOS
ON OTR_INVENTARIO = INV_INVENTARIO AND OTR_EMPRESA = INV_EMPRESA
WHERE OTR_INVENTARIO = ?
AND  OTR_MONEDA = 
(SELECT VXT_MONEDA FROM VENDEDOR_EXTRA WHERE VXT_VENDEDOR = ? AND VXT_EMPRESA = ?)
AND OTR_EMPRESA = ? 
"""

INSERT_HEADER_DEVOLUCION ="""
INSERT INTO DIST_INVDEVOLCLIH(
DINDCH_EMPRESA, 	--00  COD EMPRESA 
DINDCH_DEVNUMERO, 	--01  CORRELATIVO
DINDCH_VENDEDOR,	--02  RUTA|COD VENDEDOR
DINDCH_CLICODIGO,	--03  CODIGO CLIENTE
DINDCH_FECHA,		--04  FECHA TIPO ORDINAL  = 4589
DINDCH_TIPDEV,		--05  (WALMART : "R", UNISUPER: "V" , OTROS: "C")
DINDCH_NUMRECL,		--06  NUMERO DOC. WALMAR, UNISUPER, 
DINDCH_LOTERECL,   --07
DINDCH_FECHARECLA,	--08  FECHA DOC RECLAMO ORDINAL = 4589
DINDCH_STATUS,		--09  DEFAULT: V  (USO DE QSYSTEM)
DINDCH_NUMINVEN,	--10 DEFAULT 0 (USO DE QSYSTEM)
DINDCH_TIPINGRESO,	--11 DEFAULT "O"
DINDCH_HORA,		--12 HORA FORMATO ORDINAL 4695
DINDCH_TOTAL		--13 GRAN TOTAL SUMA DE LINEAS PRODUCTO
)
VALUES ( 
  ?,
  ?,
  ?,
  ?,
  convert(int, convert(datetime, ?,112)),
  ?,
  ?,
  ?,
  convert(int, convert(datetime, ?,112)),
  ?,
  ?,
  ?,
  ?,
  ? )
"""



INSERT_LINEA_DEVOLUCION="""
INSERT INTO DIST_INVDEVOLCLIL (
DINDCL_EMPRESA, 	--01 EMPRESA
DINDCL_DEVNUMERO, 	--02 CORRELATIVO
DINDCL_LINEA, 		--03 LINEA DETALLE DEVOLUCION
DINDCL_INVENTARIO, 	--04 CODIGO PRODUCTO
DINDCL_CANTIDAD, 	--05 CANTIDAD PRODUCTO DEV
DINDCL_PRECIOUCLI, 	--06 PRECIO U. CLIENTE
DINDCL_PRECIOUVEN, 	--07 PRECIO U. VEN
DINDCL_COSTO, 		--08 COSTO 
DINDCL_COSTOTAL, 	--09 TOTAL
DINDCL_CAUSADEV 	--10 (BUEN: "B", CALIDAD: "C", DAÑADO: "D", MOHO: "M", VENCIDO: "V")
)
VALUES( ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )
"""


CLIENTE_RUTA = """
SELECT
CLI_EMPRESA,
RTRIM(CLI_CODIGO) AS CLI_CODIGO,
RTRIM(CLI_NOMBRE) AS CLI_NOMBRE,
CLI_VENDEDOR,
EXT_MONEDA,
EXT_NIVPRECIO
FROM MASTCLI 
LEFT JOIN CLIENTES_EXTRA 
ON (CLI_CODIGO = EXT_CLIENTE AND  CLI_EMPRESA = EXT_EMPRESA)
WHERE CLI_VENDEDOR = ? AND CLI_EMPRESA = ?
ORDER BY CLI_NOMBRE
"""



GET_REGISTRO_DEVOLUCION ="""
SELECT 
--CLIENTE DATOS
RTRIM(CLI_CODIGO)AS CLI_CODIGO, 
RTRIM(CLI_NOMBRE)AS CLI_NOMBRE,
--FIN CLIENTE DATOS
EXT_MONEDA,
EXT_NIVPRECIO,
EXT_EXTRA7,
RTRIM(CLC_DESCRIPCION) AS CLC_DESCRIPCION,
EXT_EXTRA6,
RTRIM(CLA_DESCRIPCION)AS CLA_DESCRIPCION,
--DEV HEADER
RTRIM(DINDCH_EMPRESA)AS DINDCH_EMPRESA,
DINDCH_DEVNUMERO,
RTRIM(VEN_NOMBRE) AS VEN_NOMBRE,
CONVERT(DATETIME,CONVERT(INT,DINDCH_FECHA),112)AS DINDCH_FECHA,
RTRIM(DINDCH_VENDEDOR)AS DINDCH_VENDEDOR,
RTRIM(DINDCH_TIPDEV)AS DINDCH_TIPDEV,
RTRIM(DINDCH_NUMRECL)AS DINDCH_NUMRECL,
RTRIM(DINDCH_LOTERECL)AS DINDCH_LOTERECL,
CONVERT(DATETIME,CONVERT(INT,DINDCH_FECHARECLA),112)AS DINDCH_FECHARECLA,
RTRIM(DINDCH_STATUS)AS DINDCH_STATUS,
RTRIM(DINDCH_NUMINVEN)AS DINDCH_NUMINVEN,
RTRIM(DINDCH_TIPINGRESO)AS DINDCH_TIPINGRESO,
DINDCH_HORA,
CONVERT(FLOAT,DINDCH_TOTAL) AS DINDCH_TOTAL,
<<<<<<<<<<<<<<<<<<<<<<<<<<<<--FIN DEV HEDER
DINDCL_EMPRESA,
DINDCL_DEVNUMERO,
DINDCL_LINEA,
RTRIM(DINDCL_INVENTARIO) AS DINDCL_INVENTARIO,
CONVERT(FLOAT,DINDCL_CANTIDAD) AS DINDCL_CANTIDAD,
CONVERT(FLOAT,DINDCL_PRECIOUCLI) AS DINDCL_PRECIOUCLI,
CONVERT(FLOAT,DINDCL_PRECIOUVEN) AS DINDCL_PRECIOUVEN,
CONVERT(FLOAT, DINDCL_COSTO) AS DINDCL_COSTO,
CONVERT(FLOAT,DINDCL_COSTOTAL) AS DINDCL_COSTOTAL,
DINDCL_CAUSADEV
FROM DIST_INVDEVOLCLIH
LEFT JOIN MASTCLI
ON DINDCH_CLICODIGO = CLI_CODIGO AND DINDCH_EMPRESA = CLI_EMPRESA
JOIN VENDEDOR
ON VEN_CODIGO = DINDCH_VENDEDOR  AND VEN_EMPRESA = DINDCH_EMPRESA
LEFT JOIN CLIENTES_EXTRA
ON CLI_CODIGO = EXT_CLIENTE AND CLI_EMPRESA = EXT_EMPRESA
LEFT JOIN CLASI_CUENTAS_CLI
ON CLC_CODIGO = EXT_EXTRA7 AND CLI_EMPRESA = CLC_EMPRESA 
LEFT JOIN CLASIFICA_CLIENTES
ON CLA_CODIGO = EXT_EXTRA6 AND CLI_EMPRESA = CLA_EMPRESA
LEFT JOIN DIST_INVDEVOLCLIL
ON DINDCH_DEVNUMERO = DINDCL_DEVNUMERO AND DINDCH_EMPRESA = DINDCL_EMPRESA
WHERE DINDCH_DEVNUMERO =  ?
ORDER BY DINDCH_DEVNUMERO
"""