saleman = """
SELECT 
 D.DINV_EMPRESA,
 RTRIM(E.EMP_NOMBRE) AS EMP_NOMBRE,
 DINV_LINEA, 
 V.VEN_CODIGO,
 RTRIM(V.VEN_NOMBRE)AS VEN_NOMBRE
FROM DIST_INVVEND D
JOIN VENDEDOR V
 ON V.VEN_CODIGO = DINV_VENDEDOR
JOIN EMPRESA E
 ON E.EMP_CODIGO = D.DINV_EMPRESA
WHERE V.VEN_EMPRESA = D.DINV_EMPRESA
"""
customers = """
SELECT 
DINCV_VENDEDOR AS CODIGO_VENDEDOR,   
CAST(DINCV_LINEA AS INTEGER)  AS LINEA_CLIENTE_VENDEDOR,
CAST(DINCV_CLICODIGO AS INTEGER) AS CODIGO_CLIENTE,   
RTRIM(CLIENTE.CLI_NOMBRE) AS NOMBRE_CLIENTE,
RTRIM(DCLCLA_DESCRIPCION) AS DESCRIPCION_ETIQUETA,  
CLIENTE.CLI_EMPRESA AS CODIGO_EMPRESA   
FROM DIST_INVCLIVEND 
JOIN DIST_INVVEND  
ON DIST_INVVEND.DINV_VENDEDOR = DIST_INVCLIVEND.DINCV_VENDEDOR 
JOIN MASTCLI CLIENTE 
ON DIST_INVCLIVEND.DINCV_CLICODIGO = CLIENTE.CLI_CODIGO 
JOIN DIST_INVCLICLA 
ON DIST_INVCLICLA.DCLCLA_CODIGO = DIST_INVCLIVEND.DINCV_ETIQUETA
WHERE CLIENTE.CLI_EMPRESA = 'PAN'   
ORDER BY DINCV_LINEA ASC;
"""


customer_by_saleman = """ 
SELECT 
DINCV_VENDEDOR AS CODIGO_VENDEDOR,   
CAST(DINCV_LINEA AS INTEGER)  AS LINEA_CLIENTE_VENDEDOR,
CAST(DINCV_CLICODIGO AS INTEGER) AS CODIGO_CLIENTE,   
RTRIM(CLIENTE.CLI_NOMBRE) AS NOMBRE_CLIENTE,
RTRIM(DCLCLA_DESCRIPCION) AS DESCRIPCION_ETIQUETA,  
CLIENTE.CLI_EMPRESA AS CODIGO_EMPRESA   
FROM DIST_INVCLIVEND 
JOIN DIST_INVVEND  
ON DIST_INVVEND.DINV_VENDEDOR = DIST_INVCLIVEND.DINCV_VENDEDOR 
JOIN MASTCLI CLIENTE 
ON DIST_INVCLIVEND.DINCV_CLICODIGO = CLIENTE.CLI_CODIGO 
JOIN DIST_INVCLICLA 
ON DIST_INVCLICLA.DCLCLA_CODIGO = DIST_INVCLIVEND.DINCV_ETIQUETA
WHERE CLIENTE.CLI_EMPRESA = 'PAN'   
AND DIST_INVVEND.DINV_VENDEDOR = ?  
ORDER BY DINCV_LINEA ASC;
"""
product_by_saleman = """
SELECT  
DINAV_VENDEDOR AS CODIGO_VENDEDOR, 
DINAV_LINEA AS LINEA_NUMERO, 
RTRIM(DINAV_INVENTARIO) AS CODIGO_PRODUCTO, 
RTRIM(MASTINVPOS.INV_NOMBRE) AS NOMBRE_PRODUCTO
FROM DIST_INVARTSVEN 
JOIN DIST_INVVEND 
ON DINV_VENDEDOR = DIST_INVARTSVEN.DINAV_VENDEDOR   
JOIN MASTINVPOS 
ON DINAV_INVENTARIO = MASTINVPOS.INV_INVENTARIO 
WHERE DINAV_VENDEDOR = ? AND MASTINVPOS.INV_EMPRESA = 'PAN' 
"""
#detalle de devolucion y linea detalle
product_refund_by_doc_id = """
SELECT 
DD.DINDCH_EMPRESA AS EMPRESA,
DD.DINDCH_DEVNUMERO AS NUMERO_DEVOLUCION,
DD.DINDCH_VENDEDOR AS CODIGO_VENDEDOR,
RTRIM(V.VEN_NOMBRE) AS VENDEDOR,
RTRIM(DD.DINDCH_FECHA) AS FECHA_INGRESO_DEVOLUCION,
RTRIM(DD.DINDCH_HORA) AS HORA_INGRESO_DEVOLUCION,
RTRIM(DD.DINDCH_NUMRECL) AS NUMERO_DOCUMENTO_RECLAMO,
RTRIM(DD.DINDCH_LOTERECL) AS NUMERO_LOTE_RECLAMO,
RTRIM(DD.DINDCH_FECHARECLA) AS FECHA_RECLAMO,
DD.DINDCH_TIPINGRESO AS TIPO_INGRESO,
DD.DINDCH_TIPDEV AS TIPO_DEV,
DD.DINDCH_STATUS AS STATUS,
DD.DINDCH_NUMINVEN AS NUMERO_DE_INVENTARIO,
CAST (DD.DINOCH_TOTAL AS VARCHAR) AS DEV_INV_TOTAL,
DL.DINDCL_DEVNUMERO AS NUMERO_DEVOLUCION,
RTRIM(DL.DINDCL_LINEA) AS LINEA_NUMERO,
RTRIM(DL.DINDCL_INVENTARIO) AS CODIGO_PRODUCTO,
RTRIM(MASTINVPOS.INV_NOMBRE) AS NOMBRE_PRODUCTO,
CAST (DL.DINDCL_CANTIDAD AS VARCHAR) AS CANTIDAD,
CAST (DL.DINDCL_PRECIOUCLI AS VARCHAR) AS PRECIO_UNIDAD_CLIENTE,
CAST (DL.DINDCL_PRECIOUVEN AS VARCHAR) AS PRECIO_UNIDAD_VENDEDOR,
CAST (DL.DINDCL_COSTO AS VARCHAR) AS COSTO
FROM DIST_INVDEVOLCLIH DD 
LEFT JOIN DIST_INVDEVOLCLIL DL  
ON DINDCH_DEVNUMERO = DINDCL_DEVNUMERO 
LEFT JOIN MASTINVPOS
ON DL.DINDCL_INVENTARIO = MASTINVPOS.INV_INVENTARIO AND MASTINVPOS.INV_EMPRESA = DD.DINDCH_EMPRESA 
INNER JOIN VENDEDOR V 
ON DD.DINDCH_VENDEDOR = V.VEN_CODIGO AND V.VEN_EMPRESA = DD.DINDCH_EMPRESA 
WHERE DINDCH_DEVNUMERO = ?
"""

#devolucion linea 
refund_detail_by_id ="""
SELECT
DIST_INVDEVOLCLIH.DINDCH_EMPRESA AS EMPRESA,
RTRIM(DIST_INVDEVOLCLIH.DINDCH_FECHA) AS FECHA_DEVOLUCION,
RTRIM(DIST_INVDEVOLCLIH.DINDCH_HORA) AS HORA_DEVOLUCION,
RTRIM(DIST_INVDEVOLCLIH.DINDCH_FECHARECLA) AS FECHA_RECLAMO,
DIST_INVDEVOLCLIH.DINDCH_TIPDEV,
DIST_INVDEVOLCLIH.DINDCH_STATUS,
DIST_INVDEVOLCLIH.DINDCH_TIPINGRESO,
CAST(DINCV_LINEA AS INTEGER)  AS LINEA_CLIENTE_VENDEDOR,
CAST(DINCV_CLICODIGO AS INTEGER) AS CODIGO_CLIENTE,
DIST_INVDEVOLCLIH.DINDCH_VENDEDOR AS CODIGO_VENDEDOR,
RTRIM(DIST_INVDEVOLCLIH.DINDCH_NUMRECL) AS NUMERO_RECLAMO,
RTRIM(DIST_INVDEVOLCLIH.DINDCH_LOTERECL) AS LOTE_RECLAMO,
DINDCL_EMPRESA AS EMPRESA, 
DINDCL_DEVNUMERO AS NUMERO_DEVOLUCION, 
DINDCL_LINEA AS LINEA_NUMERO,
RTRIM(DINDCL_INVENTARIO) AS CODIGO_PRODUCTO, 
RTRIM(MASTINVPOS.INV_NOMBRE) AS NOMBRE_PRODUCTO, 
CAST (DINDCL_CANTIDAD AS VARCHAR) AS CANTIDAD, 
CAST (DINDCL_PRECIOUCLI AS VARCHAR) AS PRECIO_UNIDA_CLIENTE, 
CAST (DINDCL_PRECIOUVEN AS VARCHAR) AS PRECION_UNIDAD_VENDEDOR, 
CAST (DINDCL_COSTO AS VARCHAR) AS COSTO 
FROM DIST_INVDEVOLCLIL
INNER JOIN MASTINVPOS 
ON DIST_INVDEVOLCLIL.DINDCL_INVENTARIO = MASTINVPOS.INV_INVENTARIO 
INNER JOIN DIST_INVDEVOLCLIH
ON DINDCH_DEVNUMERO = DINDCL_DEVNUMERO
INNER JOIN DIST_INVCLIVEND
ON  DIST_INVCLIVEND.DINCV_CLICODIGO =  DIST_INVDEVOLCLIH.DINDCH_CLICODIGO 
AND DIST_INVCLIVEND.DINCV_VENDEDOR = DINDCH_VENDEDOR
WHERE DINDCL_DEVNUMERO=? AND MASTINVPOS.INV_EMPRESA = 'PAN'
"""

historial_devolucion_detalle = """
SELECT
DINDCH_EMPRESA,
RTRIM(DINDCH_DEVNUMERO) AS DINDCH_DEVNUMERO,
RTRIM(DINDCH_VENDEDOR) AS DINDCH_VENDEDOR,
RTRIM(DINDCH_CLICODIGO) AS DINDCH_CLICODIGO,
RTRIM(DINDCH_FECHA) AS DINDCH_FECHA,
RTRIM(DINDCH_TIPDEV) AS DINDCH_TIPDEV,
RTRIM(DINDCH_NUMRECL) AS DINDCH_NUMRECL,
RTRIM(DINDCH_LOTERECL) AS DINDCH_LOTERECL,
RTRIM(DINDCH_FECHARECLA) AS DINDCH_FECHARECLA,
DINDCH_STATUS,
DINDCH_NUMINVEN,
DINDCH_TIPINGRESO,
DINDCH_HORA,
CAST(DINOCH_TOTAL AS VARCHAR) AS DINOCH_TOTAL,
DINDCL_EMPRESA,
DINDCL_DEVNUMERO,
DINDCL_LINEA AS LINEA_NUMERO,
RTRIM(DINDCL_INVENTARIO) AS DINDCL_INVENTARIO,
CAST(DINDCL_CANTIDAD AS VARCHAR) AS DINDCL_CANTIDAD,
CAST(DINDCL_PRECIOUCLI AS VARCHAR) AS DINDCL_PRECIOUCLI,
CAST(DINDCL_PRECIOUVEN AS VARCHAR) AS DINDCL_PRECIOUVEN,
CAST(DINDCL_COSTO AS VARCHAR) AS DINDCL_COSTO
FROM
DIST_INVDEVOLCLIH,
DIST_INVDEVOLCLIL
WHERE 
DINDCH_DEVNUMERO = DINDCL_DEVNUMERO
AND DINDCH_EMPRESA = DINDCL_EMPRESA
AND DINDCL_DEVNUMERO = ?
"""






test = """ 
SELECT 
        DETALLE.DINDCH_EMPRESA AS EMPRESA,   
        DETALLE.DINDCH_DEVNUMERO AS NUMERO_DEVOLUCION,   
        DETALLE.DINDCH_VENDEDOR AS CODIGO_VENDEDOR,  
        RTRIM(V.VEN_NOMBRE) AS VENDEDOR,   
        RTRIM(DETALLE.DINDCH_FECHA) AS FECHA_INGRESO_DEVOLUCION, 
        RTRIM(DETALLE.DINDCH_HORA) AS HORA_INGRESO_DEVOLUCION,   
        RTRIM(DETALLE.DINDCH_NUMRECL) AS NUMERO_DOCUMENTO_RECLAMO,   
        RTRIM(DETALLE.DINDCH_LOTERECL) AS NUMERO_LOTE_RECLAMO,   
        RTRIM(DETALLE.DINDCH_FECHARECLA) AS FECHA_RECLAMO,   
        DETALLE.DINDCH_TIPINGRESO AS TIPO_INGRESO,   
        DETALLE.DINDCH_TIPDEV AS TIPO_DEVEVOLUCION,   
        DETALLE.DINDCH_STATUS AS STATUS, 
        DETALLE.DINDCH_NUMINVEN AS NUMERO_DE_INVENTARIO, 
        CAST (DETALLE.DINOCH_TOTAL AS VARCHAR) AS DEV_INV_TOTAL, 
        LINEA_DETALLE.DINDCL_DEVNUMERO AS NUMERO_DEVOLUCION,   
        LINEA_DETALLE.DINDCL_LINEA AS NUMERO_LINEA_DEVOLCION,  
        RTRIM(LINEA_DETALLE.DINDCL_INVENTARIO) AS CODIGO_PRODUCTO,    
        CAST (LINEA_DETALLE.DINDCL_CANTIDAD AS VARCHAR) AS CANTIDAD,   
        CAST (LINEA_DETALLE.DINDCL_PRECIOUCLI AS VARCHAR) AS PRECIO_UNIDAD_CLIENTE,    
        CAST (LINEA_DETALLE.DINDCL_PRECIOUVEN AS VARCHAR) AS PRECIO_UNIDAD_VENDEDOR,   
        CAST (LINEA_DETALLE.DINDCL_COSTO AS VARCHAR) AS COSTO  
    FROM DIST_INVDEVOLCLIH DETALLE   
        LEFT JOIN DIST_INVDEVOLCLIL LINEA_DETALLE  
    ON DINDCH_DEVNUMERO = DINDCL_DEVNUMERO  
        INNER JOIN VENDEDOR V   
    ON DETALLE.DINDCH_VENDEDOR = V.VEN_CODIGO AND V.VEN_EMPRESA = DETALLE.DINDCH_EMPRESA  
    WHERE DINDCH_DEVNUMERO = ?
"""


# buscar_duplicados="SELECT L.* FROM DIST_INVDEVOLCLIH L WHERE DINDCH_NUMRECL IN (
# SELECT DINDCH_NUMRECL FROM DIST_INVDEVOLCLIH WHERE DINDCH_NUMRECL >'' AND DINDCH_NUMRECL ='42677'
# GROUP BY DINDCH_NUMRECL 
# HAVING COUNT(*) >1
# )
buscar_y_filtrar="""
SELECT L.*, CLIENTE.CLI_NOMBRE FROM DIST_INVDEVOLCLIH L 
JOIN MASTCLI CLIENTE  
ON L.DINDCH_CLICODIGO = CLIENTE.CLI_CODIGO AND L.DINDCH_EMPRESA = CLIENTE.CLI_EMPRESA 
{}
ORDER BY DINDCH_DEVNUMERO, DINDCH_FECHA
"""
