total_reg = "SELECT COUNT(*)AS TOTAL_REGISTROS FROM MASTCLI"

customers = """ 
SELECT 
TOP 10 
CLI_AFECTO, 
RTRIM(CLI_AREA) AREA, 
RTRIM(CLI_CIUDAD) AS NOMBRE_CIUDAD, 
CLI_CLASIFICACION AS SIMBOLO_MONEDA , 
CLI_COBRADOR AS NUMERO_COBRADOR, 
RTRIM(CLI_CODIGO) AS CODIGO_CLIENTE, 
RTRIM(CLI_CONTACTO) AS NOMBRE_CONTACTO, 
RTRIM(CLI_CUENTA) AS CUENTA, 
RTRIM(CLI_DEPTO) AS NOMBRE_DEPTO, 
CLI_DIASCRED AS DIAS_CREDITO, 
RTRIM(CLI_DIRCOR1) AS DIRECCION_COBROS_1, 
RTRIM(CLI_DIRCOR2) AS DIRECCION_COBROS_2, 
RTRIM(CLI_DIRECCION) AS DIRECCION_1, 
RTRIM(CLI_DIRECCION1) AS DIRECCION_2, 
CLI_EMPRESA AS CODIGO_EMPRESA, 
RTRIM(CLI_FECHAC) AS FECHA, 
RTRIM(CLI_FEULCOMPRA) AS FECHA_ULTIMO_COMPRA, 
RTRIM(CLI_FEULPAGO) AS  FECHA_ULTIMO_PAGO  , 
CLI_LIMITE AS LIMITE_CREDITO,
RTRIM(CLI_NIT) AS NIT_CLIENTE, 
RTRIM(CLI_NOMBRE) AS NOMBRE_CLIENTE, 
CLI_PCTDESCUENTO  AS PORCENTAJE_DESCUENTO, 
RTRIM(CLI_PHONES) AS TELEFONO_CLIENTE, 
RTRIM(CLI_RUTA) AS NUMERO_RUTA, 
CLI_SALDO AS SALDO_CLIENTE,
CLI_SUSPENCION AS SUSPENCION, 
RTRIM(CLI_SUSPVFE) AS SUSPENCION_VENTA_FECHA, 
CLI_TIPO AS TIPO, 
CLI_VENDEDOR AS NUMERO_VENDEDOR, 
RTRIM(CLI_ZONA) AS ZONA 
FROM
MASTCLI
"""